# Generated by Django 2.1.2 on 2019-04-07 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='nickename',
            new_name='nickname',
        ),
    ]
